version: "3.1"

services:

  fledge-power:
    container_name: fledge-61850-scheduler-updated
    image: fledgepower/fledge-61850-scheduler-updated
    build:
      context: fledge/
      dockerfile: fledge.dockerfile
    ports:
      - "8081:8081"
      - "1995:1995"
      - "6683:6683"
      - "102:102"
      # - "1883:1883"
      # - "443:443"

    networks:
      - fledge-power

  fledge-gui:
    container_name: fledge-gui
    image: fledgepower/fledge-gui
    build:
      context: fledge-gui/
      dockerfile: fledge-gui.dockerfile
    ports:
      - "8080:80"
      # - "443:443"

    networks:
      - fledge-power

  mosquitto:
    image: eclipse-mosquitto
    container_name: test-mqtt-server
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/:/mosquitto/

networks:
  fledge-power:
    driver: bridge
